/**
 * Chinese Characters Dataset organized by grade level (1-9)
 * Based on the standard Chinese education curriculum (人教版).
 * Each character includes: character, pinyin, and English meaning.
 */

const CHARACTERS_BY_GRADE = {

  1: [
    { char: "一", pinyin: "yī", meaning: "one" },
    { char: "二", pinyin: "èr", meaning: "two" },
    { char: "三", pinyin: "sān", meaning: "three" },
    { char: "四", pinyin: "sì", meaning: "four" },
    { char: "五", pinyin: "wǔ", meaning: "five" },
    { char: "六", pinyin: "liù", meaning: "six" },
    { char: "七", pinyin: "qī", meaning: "seven" },
    { char: "八", pinyin: "bā", meaning: "eight" },
    { char: "九", pinyin: "jiǔ", meaning: "nine" },
    { char: "十", pinyin: "shí", meaning: "ten" },
    { char: "人", pinyin: "rén", meaning: "person" },
    { char: "大", pinyin: "dà", meaning: "big" },
    { char: "小", pinyin: "xiǎo", meaning: "small" },
    { char: "上", pinyin: "shàng", meaning: "up" },
    { char: "下", pinyin: "xià", meaning: "down" },
    { char: "口", pinyin: "kǒu", meaning: "mouth" },
    { char: "日", pinyin: "rì", meaning: "sun/day" },
    { char: "月", pinyin: "yuè", meaning: "moon/month" },
    { char: "水", pinyin: "shuǐ", meaning: "water" },
    { char: "火", pinyin: "huǒ", meaning: "fire" },
    { char: "山", pinyin: "shān", meaning: "mountain" },
    { char: "石", pinyin: "shí", meaning: "stone" },
    { char: "田", pinyin: "tián", meaning: "field" },
    { char: "土", pinyin: "tǔ", meaning: "earth/soil" },
    { char: "木", pinyin: "mù", meaning: "wood/tree" },
    { char: "天", pinyin: "tiān", meaning: "sky/day" },
    { char: "地", pinyin: "dì", meaning: "ground" },
    { char: "中", pinyin: "zhōng", meaning: "middle" },
    { char: "花", pinyin: "huā", meaning: "flower" },
    { char: "草", pinyin: "cǎo", meaning: "grass" },
    { char: "鸟", pinyin: "niǎo", meaning: "bird" },
    { char: "鱼", pinyin: "yú", meaning: "fish" },
    { char: "虫", pinyin: "chóng", meaning: "insect" },
    { char: "马", pinyin: "mǎ", meaning: "horse" },
    { char: "牛", pinyin: "niú", meaning: "cow" },
    { char: "羊", pinyin: "yáng", meaning: "sheep" },
    { char: "犬", pinyin: "quǎn", meaning: "dog" },
    { char: "目", pinyin: "mù", meaning: "eye" },
    { char: "耳", pinyin: "ěr", meaning: "ear" },
    { char: "手", pinyin: "shǒu", meaning: "hand" },
    { char: "足", pinyin: "zú", meaning: "foot" },
    { char: "白", pinyin: "bái", meaning: "white" },
    { char: "云", pinyin: "yún", meaning: "cloud" },
    { char: "雨", pinyin: "yǔ", meaning: "rain" },
    { char: "风", pinyin: "fēng", meaning: "wind" },
    { char: "男", pinyin: "nán", meaning: "male" },
    { char: "女", pinyin: "nǚ", meaning: "female" },
    { char: "子", pinyin: "zǐ", meaning: "child" },
    { char: "我", pinyin: "wǒ", meaning: "I/me" },
    { char: "你", pinyin: "nǐ", meaning: "you" },
    { char: "他", pinyin: "tā", meaning: "he/him" },
    { char: "她", pinyin: "tā", meaning: "she/her" },
    { char: "好", pinyin: "hǎo", meaning: "good" },
    { char: "不", pinyin: "bù", meaning: "not" },
    { char: "是", pinyin: "shì", meaning: "is/yes" },
    { char: "了", pinyin: "le", meaning: "(completed)" },
    { char: "在", pinyin: "zài", meaning: "at/in" },
    { char: "有", pinyin: "yǒu", meaning: "have" },
    { char: "来", pinyin: "lái", meaning: "come" },
    { char: "去", pinyin: "qù", meaning: "go" },
  ],

  2: [
    { char: "春", pinyin: "chūn", meaning: "spring" },
    { char: "夏", pinyin: "xià", meaning: "summer" },
    { char: "秋", pinyin: "qiū", meaning: "autumn" },
    { char: "冬", pinyin: "dōng", meaning: "winter" },
    { char: "东", pinyin: "dōng", meaning: "east" },
    { char: "西", pinyin: "xī", meaning: "west" },
    { char: "南", pinyin: "nán", meaning: "south" },
    { char: "北", pinyin: "běi", meaning: "north" },
    { char: "前", pinyin: "qián", meaning: "front" },
    { char: "后", pinyin: "hòu", meaning: "back/after" },
    { char: "左", pinyin: "zuǒ", meaning: "left" },
    { char: "右", pinyin: "yòu", meaning: "right" },
    { char: "红", pinyin: "hóng", meaning: "red" },
    { char: "黄", pinyin: "huáng", meaning: "yellow" },
    { char: "蓝", pinyin: "lán", meaning: "blue" },
    { char: "绿", pinyin: "lǜ", meaning: "green" },
    { char: "黑", pinyin: "hēi", meaning: "black" },
    { char: "多", pinyin: "duō", meaning: "many" },
    { char: "少", pinyin: "shǎo", meaning: "few" },
    { char: "长", pinyin: "cháng", meaning: "long" },
    { char: "短", pinyin: "duǎn", meaning: "short" },
    { char: "高", pinyin: "gāo", meaning: "tall/high" },
    { char: "低", pinyin: "dī", meaning: "low" },
    { char: "快", pinyin: "kuài", meaning: "fast" },
    { char: "慢", pinyin: "màn", meaning: "slow" },
    { char: "老", pinyin: "lǎo", meaning: "old" },
    { char: "新", pinyin: "xīn", meaning: "new" },
    { char: "早", pinyin: "zǎo", meaning: "early/morning" },
    { char: "晚", pinyin: "wǎn", meaning: "late/evening" },
    { char: "明", pinyin: "míng", meaning: "bright" },
    { char: "星", pinyin: "xīng", meaning: "star" },
    { char: "家", pinyin: "jiā", meaning: "home/family" },
    { char: "门", pinyin: "mén", meaning: "door" },
    { char: "窗", pinyin: "chuāng", meaning: "window" },
    { char: "桌", pinyin: "zhuō", meaning: "table" },
    { char: "椅", pinyin: "yǐ", meaning: "chair" },
    { char: "书", pinyin: "shū", meaning: "book" },
    { char: "笔", pinyin: "bǐ", meaning: "pen" },
    { char: "纸", pinyin: "zhǐ", meaning: "paper" },
    { char: "吃", pinyin: "chī", meaning: "eat" },
    { char: "喝", pinyin: "hē", meaning: "drink" },
    { char: "看", pinyin: "kàn", meaning: "look/see" },
    { char: "听", pinyin: "tīng", meaning: "listen" },
    { char: "说", pinyin: "shuō", meaning: "speak" },
    { char: "读", pinyin: "dú", meaning: "read" },
    { char: "写", pinyin: "xiě", meaning: "write" },
    { char: "走", pinyin: "zǒu", meaning: "walk" },
    { char: "跑", pinyin: "pǎo", meaning: "run" },
    { char: "飞", pinyin: "fēi", meaning: "fly" },
    { char: "爸", pinyin: "bà", meaning: "dad" },
    { char: "妈", pinyin: "mā", meaning: "mom" },
    { char: "哥", pinyin: "gē", meaning: "older brother" },
    { char: "姐", pinyin: "jiě", meaning: "older sister" },
    { char: "弟", pinyin: "dì", meaning: "younger brother" },
    { char: "妹", pinyin: "mèi", meaning: "younger sister" },
    { char: "朋", pinyin: "péng", meaning: "friend (part)" },
    { char: "友", pinyin: "yǒu", meaning: "friend" },
    { char: "学", pinyin: "xué", meaning: "study/learn" },
    { char: "校", pinyin: "xiào", meaning: "school" },
    { char: "师", pinyin: "shī", meaning: "teacher" },
  ],

  3: [
    { char: "语", pinyin: "yǔ", meaning: "language" },
    { char: "文", pinyin: "wén", meaning: "writing/culture" },
    { char: "数", pinyin: "shù", meaning: "number/math" },
    { char: "音", pinyin: "yīn", meaning: "sound" },
    { char: "乐", pinyin: "yuè", meaning: "music/joy" },
    { char: "画", pinyin: "huà", meaning: "draw/painting" },
    { char: "体", pinyin: "tǐ", meaning: "body" },
    { char: "育", pinyin: "yù", meaning: "education" },
    { char: "科", pinyin: "kē", meaning: "science/subject" },
    { char: "课", pinyin: "kè", meaning: "class/lesson" },
    { char: "教", pinyin: "jiāo", meaning: "teach" },
    { char: "习", pinyin: "xí", meaning: "practice" },
    { char: "作", pinyin: "zuò", meaning: "make/work" },
    { char: "业", pinyin: "yè", meaning: "work/industry" },
    { char: "考", pinyin: "kǎo", meaning: "test/exam" },
    { char: "试", pinyin: "shì", meaning: "try/test" },
    { char: "答", pinyin: "dá", meaning: "answer" },
    { char: "问", pinyin: "wèn", meaning: "ask" },
    { char: "想", pinyin: "xiǎng", meaning: "think/want" },
    { char: "知", pinyin: "zhī", meaning: "know" },
    { char: "道", pinyin: "dào", meaning: "way/road" },
    { char: "会", pinyin: "huì", meaning: "can/meet" },
    { char: "能", pinyin: "néng", meaning: "able/can" },
    { char: "做", pinyin: "zuò", meaning: "do/make" },
    { char: "用", pinyin: "yòng", meaning: "use" },
    { char: "玩", pinyin: "wán", meaning: "play" },
    { char: "唱", pinyin: "chàng", meaning: "sing" },
    { char: "跳", pinyin: "tiào", meaning: "jump/dance" },
    { char: "笑", pinyin: "xiào", meaning: "laugh/smile" },
    { char: "哭", pinyin: "kū", meaning: "cry" },
    { char: "爱", pinyin: "ài", meaning: "love" },
    { char: "心", pinyin: "xīn", meaning: "heart" },
    { char: "开", pinyin: "kāi", meaning: "open" },
    { char: "关", pinyin: "guān", meaning: "close/off" },
    { char: "头", pinyin: "tóu", meaning: "head" },
    { char: "脸", pinyin: "liǎn", meaning: "face" },
    { char: "鼻", pinyin: "bí", meaning: "nose" },
    { char: "牙", pinyin: "yá", meaning: "tooth" },
    { char: "发", pinyin: "fà", meaning: "hair" },
    { char: "身", pinyin: "shēn", meaning: "body" },
    { char: "站", pinyin: "zhàn", meaning: "stand" },
    { char: "坐", pinyin: "zuò", meaning: "sit" },
    { char: "睡", pinyin: "shuì", meaning: "sleep" },
    { char: "醒", pinyin: "xǐng", meaning: "wake up" },
    { char: "穿", pinyin: "chuān", meaning: "wear" },
    { char: "衣", pinyin: "yī", meaning: "clothes" },
    { char: "帽", pinyin: "mào", meaning: "hat" },
    { char: "鞋", pinyin: "xié", meaning: "shoe" },
    { char: "饭", pinyin: "fàn", meaning: "rice/meal" },
    { char: "菜", pinyin: "cài", meaning: "vegetable/dish" },
    { char: "米", pinyin: "mǐ", meaning: "rice (grain)" },
    { char: "面", pinyin: "miàn", meaning: "noodle/face" },
    { char: "茶", pinyin: "chá", meaning: "tea" },
    { char: "糖", pinyin: "táng", meaning: "sugar/candy" },
    { char: "果", pinyin: "guǒ", meaning: "fruit/result" },
    { char: "瓜", pinyin: "guā", meaning: "melon" },
    { char: "树", pinyin: "shù", meaning: "tree" },
    { char: "叶", pinyin: "yè", meaning: "leaf" },
    { char: "根", pinyin: "gēn", meaning: "root" },
    { char: "种", pinyin: "zhǒng", meaning: "seed/kind" },
  ],

  4: [
    { char: "城", pinyin: "chéng", meaning: "city" },
    { char: "市", pinyin: "shì", meaning: "city/market" },
    { char: "村", pinyin: "cūn", meaning: "village" },
    { char: "路", pinyin: "lù", meaning: "road" },
    { char: "桥", pinyin: "qiáo", meaning: "bridge" },
    { char: "河", pinyin: "hé", meaning: "river" },
    { char: "海", pinyin: "hǎi", meaning: "sea" },
    { char: "湖", pinyin: "hú", meaning: "lake" },
    { char: "岛", pinyin: "dǎo", meaning: "island" },
    { char: "林", pinyin: "lín", meaning: "forest" },
    { char: "园", pinyin: "yuán", meaning: "garden/park" },
    { char: "店", pinyin: "diàn", meaning: "shop/store" },
    { char: "院", pinyin: "yuàn", meaning: "yard/court" },
    { char: "楼", pinyin: "lóu", meaning: "building/floor" },
    { char: "厅", pinyin: "tīng", meaning: "hall" },
    { char: "厨", pinyin: "chú", meaning: "kitchen" },
    { char: "房", pinyin: "fáng", meaning: "room/house" },
    { char: "车", pinyin: "chē", meaning: "car/vehicle" },
    { char: "船", pinyin: "chuán", meaning: "boat/ship" },
    { char: "机", pinyin: "jī", meaning: "machine/plane" },
    { char: "电", pinyin: "diàn", meaning: "electricity" },
    { char: "灯", pinyin: "dēng", meaning: "lamp/light" },
    { char: "话", pinyin: "huà", meaning: "speech/word" },
    { char: "视", pinyin: "shì", meaning: "view/TV" },
    { char: "脑", pinyin: "nǎo", meaning: "brain" },
    { char: "钟", pinyin: "zhōng", meaning: "clock/bell" },
    { char: "表", pinyin: "biǎo", meaning: "watch/table" },
    { char: "猫", pinyin: "māo", meaning: "cat" },
    { char: "狗", pinyin: "gǒu", meaning: "dog" },
    { char: "兔", pinyin: "tù", meaning: "rabbit" },
    { char: "龙", pinyin: "lóng", meaning: "dragon" },
    { char: "蛇", pinyin: "shé", meaning: "snake" },
    { char: "虎", pinyin: "hǔ", meaning: "tiger" },
    { char: "猴", pinyin: "hóu", meaning: "monkey" },
    { char: "鸡", pinyin: "jī", meaning: "chicken" },
    { char: "鸭", pinyin: "yā", meaning: "duck" },
    { char: "猪", pinyin: "zhū", meaning: "pig" },
    { char: "象", pinyin: "xiàng", meaning: "elephant" },
    { char: "蝴", pinyin: "hú", meaning: "butterfly (part)" },
    { char: "蝶", pinyin: "dié", meaning: "butterfly" },
    { char: "找", pinyin: "zhǎo", meaning: "find/look for" },
    { char: "给", pinyin: "gěi", meaning: "give" },
    { char: "送", pinyin: "sòng", meaning: "send/give" },
    { char: "买", pinyin: "mǎi", meaning: "buy" },
    { char: "卖", pinyin: "mài", meaning: "sell" },
    { char: "借", pinyin: "jiè", meaning: "borrow/lend" },
    { char: "还", pinyin: "huán", meaning: "return/still" },
    { char: "带", pinyin: "dài", meaning: "bring/belt" },
    { char: "让", pinyin: "ràng", meaning: "let/allow" },
    { char: "帮", pinyin: "bāng", meaning: "help" },
    { char: "忙", pinyin: "máng", meaning: "busy" },
    { char: "累", pinyin: "lèi", meaning: "tired" },
    { char: "病", pinyin: "bìng", meaning: "sick/illness" },
    { char: "药", pinyin: "yào", meaning: "medicine" },
    { char: "医", pinyin: "yī", meaning: "doctor/medical" },
    { char: "年", pinyin: "nián", meaning: "year" },
    { char: "节", pinyin: "jié", meaning: "festival/holiday" },
    { char: "假", pinyin: "jià", meaning: "holiday/fake" },
    { char: "礼", pinyin: "lǐ", meaning: "gift/ceremony" },
    { char: "物", pinyin: "wù", meaning: "thing/object" },
  ],

  5: [
    { char: "国", pinyin: "guó", meaning: "country" },
    { char: "民", pinyin: "mín", meaning: "people" },
    { char: "族", pinyin: "zú", meaning: "ethnic group" },
    { char: "旗", pinyin: "qí", meaning: "flag" },
    { char: "歌", pinyin: "gē", meaning: "song" },
    { char: "军", pinyin: "jūn", meaning: "army" },
    { char: "战", pinyin: "zhàn", meaning: "war/battle" },
    { char: "和", pinyin: "hé", meaning: "and/peace" },
    { char: "平", pinyin: "píng", meaning: "flat/peace" },
    { char: "安", pinyin: "ān", meaning: "safe/peace" },
    { char: "全", pinyin: "quán", meaning: "complete/safe" },
    { char: "危", pinyin: "wēi", meaning: "danger" },
    { char: "险", pinyin: "xiǎn", meaning: "danger/risk" },
    { char: "勇", pinyin: "yǒng", meaning: "brave" },
    { char: "敢", pinyin: "gǎn", meaning: "dare" },
    { char: "强", pinyin: "qiáng", meaning: "strong" },
    { char: "弱", pinyin: "ruò", meaning: "weak" },
    { char: "胜", pinyin: "shèng", meaning: "win/victory" },
    { char: "败", pinyin: "bài", meaning: "lose/defeat" },
    { char: "比", pinyin: "bǐ", meaning: "compare" },
    { char: "赛", pinyin: "sài", meaning: "compete/race" },
    { char: "赢", pinyin: "yíng", meaning: "win" },
    { char: "输", pinyin: "shū", meaning: "lose" },
    { char: "练", pinyin: "liàn", meaning: "practice" },
    { char: "功", pinyin: "gōng", meaning: "merit/kung fu" },
    { char: "夫", pinyin: "fū", meaning: "man/husband" },
    { char: "力", pinyin: "lì", meaning: "strength/power" },
    { char: "气", pinyin: "qì", meaning: "air/energy" },
    { char: "运", pinyin: "yùn", meaning: "luck/transport" },
    { char: "动", pinyin: "dòng", meaning: "move" },
    { char: "球", pinyin: "qiú", meaning: "ball" },
    { char: "游", pinyin: "yóu", meaning: "swim/travel" },
    { char: "泳", pinyin: "yǒng", meaning: "swim" },
    { char: "骑", pinyin: "qí", meaning: "ride" },
    { char: "推", pinyin: "tuī", meaning: "push" },
    { char: "拉", pinyin: "lā", meaning: "pull" },
    { char: "拿", pinyin: "ná", meaning: "take/hold" },
    { char: "放", pinyin: "fàng", meaning: "put/release" },
    { char: "扔", pinyin: "rēng", meaning: "throw" },
    { char: "接", pinyin: "jiē", meaning: "catch/connect" },
    { char: "抓", pinyin: "zhuā", meaning: "grab" },
    { char: "打", pinyin: "dǎ", meaning: "hit/play" },
    { char: "踢", pinyin: "tī", meaning: "kick" },
    { char: "叫", pinyin: "jiào", meaning: "call/shout" },
    { char: "喊", pinyin: "hǎn", meaning: "shout/yell" },
    { char: "告", pinyin: "gào", meaning: "tell/inform" },
    { char: "诉", pinyin: "sù", meaning: "tell/complain" },
    { char: "谢", pinyin: "xiè", meaning: "thank" },
    { char: "请", pinyin: "qǐng", meaning: "please/invite" },
    { char: "欢", pinyin: "huān", meaning: "happy/joyful" },
    { char: "迎", pinyin: "yíng", meaning: "welcome" },
    { char: "回", pinyin: "huí", meaning: "return" },
    { char: "到", pinyin: "dào", meaning: "arrive/to" },
    { char: "过", pinyin: "guò", meaning: "pass/cross" },
    { char: "进", pinyin: "jìn", meaning: "enter" },
    { char: "出", pinyin: "chū", meaning: "exit/go out" },
    { char: "起", pinyin: "qǐ", meaning: "rise/get up" },
    { char: "落", pinyin: "luò", meaning: "fall/drop" },
    { char: "升", pinyin: "shēng", meaning: "rise/ascend" },
    { char: "降", pinyin: "jiàng", meaning: "descend/fall" },
  ],

  6: [
    { char: "理", pinyin: "lǐ", meaning: "reason/manage" },
    { char: "解", pinyin: "jiě", meaning: "understand" },
    { char: "思", pinyin: "sī", meaning: "think" },
    { char: "念", pinyin: "niàn", meaning: "read/miss" },
    { char: "记", pinyin: "jì", meaning: "remember" },
    { char: "忘", pinyin: "wàng", meaning: "forget" },
    { char: "认", pinyin: "rèn", meaning: "recognize" },
    { char: "识", pinyin: "shí", meaning: "know/knowledge" },
    { char: "感", pinyin: "gǎn", meaning: "feel/sense" },
    { char: "觉", pinyin: "jué", meaning: "feel/sense" },
    { char: "情", pinyin: "qíng", meaning: "feeling/emotion" },
    { char: "意", pinyin: "yì", meaning: "meaning/intent" },
    { char: "志", pinyin: "zhì", meaning: "will/ambition" },
    { char: "愿", pinyin: "yuàn", meaning: "wish/willing" },
    { char: "望", pinyin: "wàng", meaning: "hope/look" },
    { char: "梦", pinyin: "mèng", meaning: "dream" },
    { char: "信", pinyin: "xìn", meaning: "believe/letter" },
    { char: "任", pinyin: "rèn", meaning: "duty/appoint" },
    { char: "责", pinyin: "zé", meaning: "responsibility" },
    { char: "勤", pinyin: "qín", meaning: "diligent" },
    { char: "劳", pinyin: "láo", meaning: "labor/toil" },
    { char: "苦", pinyin: "kǔ", meaning: "bitter/hard" },
    { char: "甜", pinyin: "tián", meaning: "sweet" },
    { char: "酸", pinyin: "suān", meaning: "sour" },
    { char: "辣", pinyin: "là", meaning: "spicy" },
    { char: "咸", pinyin: "xián", meaning: "salty" },
    { char: "香", pinyin: "xiāng", meaning: "fragrant" },
    { char: "臭", pinyin: "chòu", meaning: "smelly" },
    { char: "冷", pinyin: "lěng", meaning: "cold" },
    { char: "热", pinyin: "rè", meaning: "hot" },
    { char: "暖", pinyin: "nuǎn", meaning: "warm" },
    { char: "凉", pinyin: "liáng", meaning: "cool" },
    { char: "干", pinyin: "gān", meaning: "dry" },
    { char: "湿", pinyin: "shī", meaning: "wet" },
    { char: "深", pinyin: "shēn", meaning: "deep" },
    { char: "浅", pinyin: "qiǎn", meaning: "shallow" },
    { char: "宽", pinyin: "kuān", meaning: "wide" },
    { char: "窄", pinyin: "zhǎi", meaning: "narrow" },
    { char: "厚", pinyin: "hòu", meaning: "thick" },
    { char: "薄", pinyin: "báo", meaning: "thin" },
    { char: "重", pinyin: "zhòng", meaning: "heavy" },
    { char: "轻", pinyin: "qīng", meaning: "light (weight)" },
    { char: "困", pinyin: "kùn", meaning: "sleepy/stuck" },
    { char: "难", pinyin: "nán", meaning: "difficult" },
    { char: "易", pinyin: "yì", meaning: "easy" },
    { char: "简", pinyin: "jiǎn", meaning: "simple" },
    { char: "单", pinyin: "dān", meaning: "single/simple" },
    { char: "复", pinyin: "fù", meaning: "complex/repeat" },
    { char: "杂", pinyin: "zá", meaning: "mixed/messy" },
    { char: "整", pinyin: "zhěng", meaning: "tidy/whole" },
    { char: "齐", pinyin: "qí", meaning: "neat/even" },
    { char: "乱", pinyin: "luàn", meaning: "messy/chaos" },
    { char: "静", pinyin: "jìng", meaning: "quiet/still" },
    { char: "闹", pinyin: "nào", meaning: "noisy" },
    { char: "忽", pinyin: "hū", meaning: "suddenly" },
    { char: "然", pinyin: "rán", meaning: "so/but" },
    { char: "或", pinyin: "huò", meaning: "or" },
    { char: "但", pinyin: "dàn", meaning: "but" },
    { char: "因", pinyin: "yīn", meaning: "because" },
    { char: "所", pinyin: "suǒ", meaning: "place/so" },
  ],

  7: [
    { char: "政", pinyin: "zhèng", meaning: "politics" },
    { char: "府", pinyin: "fǔ", meaning: "government" },
    { char: "法", pinyin: "fǎ", meaning: "law/method" },
    { char: "律", pinyin: "lǜ", meaning: "law/rule" },
    { char: "制", pinyin: "zhì", meaning: "system/make" },
    { char: "度", pinyin: "dù", meaning: "degree/system" },
    { char: "规", pinyin: "guī", meaning: "rule/regulation" },
    { char: "则", pinyin: "zé", meaning: "rule/principle" },
    { char: "权", pinyin: "quán", meaning: "right/power" },
    { char: "利", pinyin: "lì", meaning: "benefit/sharp" },
    { char: "义", pinyin: "yì", meaning: "justice/meaning" },
    { char: "务", pinyin: "wù", meaning: "duty/must" },
    { char: "社", pinyin: "shè", meaning: "society" },
    { char: "区", pinyin: "qū", meaning: "district/area" },
    { char: "省", pinyin: "shěng", meaning: "province/save" },
    { char: "县", pinyin: "xiàn", meaning: "county" },
    { char: "镇", pinyin: "zhèn", meaning: "town" },
    { char: "街", pinyin: "jiē", meaning: "street" },
    { char: "馆", pinyin: "guǎn", meaning: "hall/museum" },
    { char: "站", pinyin: "zhàn", meaning: "station/stand" },
    { char: "港", pinyin: "gǎng", meaning: "port/harbor" },
    { char: "航", pinyin: "háng", meaning: "navigate/fly" },
    { char: "洲", pinyin: "zhōu", meaning: "continent" },
    { char: "界", pinyin: "jiè", meaning: "world/boundary" },
    { char: "际", pinyin: "jì", meaning: "occasion/border" },
    { char: "境", pinyin: "jìng", meaning: "boundary/state" },
    { char: "环", pinyin: "huán", meaning: "ring/surround" },
    { char: "保", pinyin: "bǎo", meaning: "protect/keep" },
    { char: "护", pinyin: "hù", meaning: "protect/guard" },
    { char: "污", pinyin: "wū", meaning: "pollute/dirty" },
    { char: "染", pinyin: "rǎn", meaning: "dye/pollute" },
    { char: "净", pinyin: "jìng", meaning: "clean/pure" },
    { char: "废", pinyin: "fèi", meaning: "waste/discard" },
    { char: "收", pinyin: "shōu", meaning: "receive/collect" },
    { char: "集", pinyin: "jí", meaning: "gather/collect" },
    { char: "农", pinyin: "nóng", meaning: "agriculture" },
    { char: "工", pinyin: "gōng", meaning: "work/craft" },
    { char: "商", pinyin: "shāng", meaning: "business" },
    { char: "厂", pinyin: "chǎng", meaning: "factory" },
    { char: "银", pinyin: "yín", meaning: "silver/bank" },
    { char: "钱", pinyin: "qián", meaning: "money" },
    { char: "价", pinyin: "jià", meaning: "price" },
    { char: "值", pinyin: "zhí", meaning: "value/worth" },
    { char: "富", pinyin: "fù", meaning: "rich/wealthy" },
    { char: "穷", pinyin: "qióng", meaning: "poor" },
    { char: "贵", pinyin: "guì", meaning: "expensive/noble" },
    { char: "便", pinyin: "pián", meaning: "cheap/convenient" },
    { char: "算", pinyin: "suàn", meaning: "calculate" },
    { char: "查", pinyin: "chá", meaning: "check/search" },
    { char: "验", pinyin: "yàn", meaning: "verify/test" },
    { char: "究", pinyin: "jiū", meaning: "investigate" },
    { char: "研", pinyin: "yán", meaning: "research" },
    { char: "究", pinyin: "jiū", meaning: "study/research" },
    { char: "实", pinyin: "shí", meaning: "real/solid" },
    { char: "际", pinyin: "jì", meaning: "actual/border" },
    { char: "确", pinyin: "què", meaning: "certain/sure" },
    { char: "定", pinyin: "dìng", meaning: "decide/fixed" },
    { char: "必", pinyin: "bì", meaning: "must/certain" },
    { char: "须", pinyin: "xū", meaning: "must/need" },
    { char: "应", pinyin: "yīng", meaning: "should/respond" },
  ],

  8: [
    { char: "历", pinyin: "lì", meaning: "history/pass" },
    { char: "史", pinyin: "shǐ", meaning: "history" },
    { char: "古", pinyin: "gǔ", meaning: "ancient" },
    { char: "代", pinyin: "dài", meaning: "era/generation" },
    { char: "朝", pinyin: "cháo", meaning: "dynasty/morning" },
    { char: "皇", pinyin: "huáng", meaning: "emperor" },
    { char: "帝", pinyin: "dì", meaning: "emperor" },
    { char: "王", pinyin: "wáng", meaning: "king" },
    { char: "臣", pinyin: "chén", meaning: "minister" },
    { char: "官", pinyin: "guān", meaning: "official" },
    { char: "将", pinyin: "jiāng", meaning: "general/will" },
    { char: "兵", pinyin: "bīng", meaning: "soldier" },
    { char: "剑", pinyin: "jiàn", meaning: "sword" },
    { char: "弓", pinyin: "gōng", meaning: "bow" },
    { char: "箭", pinyin: "jiàn", meaning: "arrow" },
    { char: "盾", pinyin: "dùn", meaning: "shield" },
    { char: "旅", pinyin: "lǚ", meaning: "travel" },
    { char: "途", pinyin: "tú", meaning: "journey/road" },
    { char: "探", pinyin: "tàn", meaning: "explore" },
    { char: "险", pinyin: "xiǎn", meaning: "dangerous" },
    { char: "宝", pinyin: "bǎo", meaning: "treasure" },
    { char: "藏", pinyin: "cáng", meaning: "hide/store" },
    { char: "密", pinyin: "mì", meaning: "secret/dense" },
    { char: "秘", pinyin: "mì", meaning: "secret" },
    { char: "谜", pinyin: "mí", meaning: "riddle/mystery" },
    { char: "智", pinyin: "zhì", meaning: "wisdom" },
    { char: "慧", pinyin: "huì", meaning: "intelligent" },
    { char: "聪", pinyin: "cōng", meaning: "clever/smart" },
    { char: "巧", pinyin: "qiǎo", meaning: "clever/skillful" },
    { char: "妙", pinyin: "miào", meaning: "wonderful" },
    { char: "奇", pinyin: "qí", meaning: "strange/wonder" },
    { char: "怪", pinyin: "guài", meaning: "strange/blame" },
    { char: "神", pinyin: "shén", meaning: "god/spirit" },
    { char: "仙", pinyin: "xiān", meaning: "fairy/immortal" },
    { char: "魔", pinyin: "mó", meaning: "demon/magic" },
    { char: "鬼", pinyin: "guǐ", meaning: "ghost" },
    { char: "灵", pinyin: "líng", meaning: "spirit/clever" },
    { char: "魂", pinyin: "hún", meaning: "soul" },
    { char: "诗", pinyin: "shī", meaning: "poem/poetry" },
    { char: "词", pinyin: "cí", meaning: "word/lyrics" },
    { char: "句", pinyin: "jù", meaning: "sentence" },
    { char: "章", pinyin: "zhāng", meaning: "chapter" },
    { char: "篇", pinyin: "piān", meaning: "article/piece" },
    { char: "故", pinyin: "gù", meaning: "old/reason/story" },
    { char: "事", pinyin: "shì", meaning: "thing/event" },
    { char: "传", pinyin: "chuán", meaning: "pass on/story" },
    { char: "说", pinyin: "shuō", meaning: "speak/novel" },
    { char: "描", pinyin: "miáo", meaning: "describe/draw" },
    { char: "述", pinyin: "shù", meaning: "narrate/state" },
    { char: "论", pinyin: "lùn", meaning: "discuss/theory" },
    { char: "证", pinyin: "zhèng", meaning: "prove/evidence" },
    { char: "据", pinyin: "jù", meaning: "evidence/base" },
    { char: "例", pinyin: "lì", meaning: "example" },
    { char: "类", pinyin: "lèi", meaning: "type/kind" },
    { char: "似", pinyin: "sì", meaning: "similar/like" },
    { char: "若", pinyin: "ruò", meaning: "if/like" },
    { char: "虽", pinyin: "suī", meaning: "although" },
    { char: "仍", pinyin: "réng", meaning: "still/yet" },
    { char: "即", pinyin: "jí", meaning: "immediately/i.e." },
    { char: "既", pinyin: "jì", meaning: "already/since" },
  ],

  9: [
    { char: "哲", pinyin: "zhé", meaning: "philosophy" },
    { char: "逻", pinyin: "luó", meaning: "logic (part)" },
    { char: "辑", pinyin: "jí", meaning: "logic/compile" },
    { char: "抽", pinyin: "chōu", meaning: "abstract/draw" },
    { char: "象", pinyin: "xiàng", meaning: "elephant/image" },
    { char: "概", pinyin: "gài", meaning: "general/approx" },
    { char: "质", pinyin: "zhì", meaning: "quality/matter" },
    { char: "量", pinyin: "liàng", meaning: "quantity/measure" },
    { char: "变", pinyin: "biàn", meaning: "change" },
    { char: "化", pinyin: "huà", meaning: "change/transform" },
    { char: "式", pinyin: "shì", meaning: "style/formula" },
    { char: "型", pinyin: "xíng", meaning: "type/model" },
    { char: "构", pinyin: "gòu", meaning: "structure/build" },
    { char: "造", pinyin: "zào", meaning: "make/build" },
    { char: "设", pinyin: "shè", meaning: "design/set up" },
    { char: "计", pinyin: "jì", meaning: "plan/calculate" },
    { char: "策", pinyin: "cè", meaning: "plan/strategy" },
    { char: "略", pinyin: "lüè", meaning: "strategy/brief" },
    { char: "效", pinyin: "xiào", meaning: "effect/imitate" },
    { char: "率", pinyin: "lǜ", meaning: "rate/efficiency" },
    { char: "续", pinyin: "xù", meaning: "continue" },
    { char: "持", pinyin: "chí", meaning: "hold/maintain" },
    { char: "展", pinyin: "zhǎn", meaning: "expand/exhibit" },
    { char: "望", pinyin: "wàng", meaning: "hope/gaze" },
    { char: "创", pinyin: "chuàng", meaning: "create/initiate" },
    { char: "新", pinyin: "xīn", meaning: "new/novel" },
    { char: "革", pinyin: "gé", meaning: "reform/leather" },
    { char: "命", pinyin: "mìng", meaning: "life/fate/order" },
    { char: "技", pinyin: "jì", meaning: "skill/technology" },
    { char: "术", pinyin: "shù", meaning: "art/technique" },
    { char: "器", pinyin: "qì", meaning: "tool/instrument" },
    { char: "材", pinyin: "cái", meaning: "material/talent" },
    { char: "源", pinyin: "yuán", meaning: "source/origin" },
    { char: "能", pinyin: "néng", meaning: "energy/ability" },
    { char: "核", pinyin: "hé", meaning: "nuclear/core" },
    { char: "素", pinyin: "sù", meaning: "element/plain" },
    { char: "基", pinyin: "jī", meaning: "base/foundation" },
    { char: "础", pinyin: "chǔ", meaning: "foundation" },
    { char: "端", pinyin: "duān", meaning: "end/proper" },
    { char: "层", pinyin: "céng", meaning: "layer/floor" },
    { char: "级", pinyin: "jí", meaning: "level/grade" },
    { char: "段", pinyin: "duàn", meaning: "section/period" },
    { char: "序", pinyin: "xù", meaning: "order/sequence" },
    { char: "系", pinyin: "xì", meaning: "system/connect" },
    { char: "统", pinyin: "tǒng", meaning: "unite/system" },
    { char: "组", pinyin: "zǔ", meaning: "group/organize" },
    { char: "织", pinyin: "zhī", meaning: "weave/organize" },
    { char: "协", pinyin: "xié", meaning: "cooperate" },
    { char: "调", pinyin: "tiáo", meaning: "adjust/tune" },
    { char: "配", pinyin: "pèi", meaning: "match/allocate" },
    { char: "合", pinyin: "hé", meaning: "combine/fit" },
    { char: "适", pinyin: "shì", meaning: "suitable/fit" },
    { char: "称", pinyin: "chēng", meaning: "call/weigh" },
    { char: "衡", pinyin: "héng", meaning: "balance/weigh" },
    { char: "均", pinyin: "jūn", meaning: "equal/even" },
    { char: "匀", pinyin: "yún", meaning: "even/uniform" },
    { char: "恒", pinyin: "héng", meaning: "constant/eternal" },
    { char: "永", pinyin: "yǒng", meaning: "forever/eternal" },
    { char: "久", pinyin: "jiǔ", meaning: "long time" },
    { char: "终", pinyin: "zhōng", meaning: "end/final" },
  ]
};

// Helper: get all characters for a given grade range
function getCharactersForGrades(minGrade, maxGrade) {
  let result = [];
  for (let g = minGrade; g <= maxGrade; g++) {
    if (CHARACTERS_BY_GRADE[g]) {
      result = result.concat(CHARACTERS_BY_GRADE[g]);
    }
  }
  return result;
}

// Helper: get character count for a grade
function getGradeCharCount(grade) {
  return CHARACTERS_BY_GRADE[grade] ? CHARACTERS_BY_GRADE[grade].length : 0;
}
