#!/usr/bin/env python3
"""Generate a printable HTML page of characters broken down by grade.

Open the output file in a browser and use File → Print (or Ctrl/Cmd-P)
to save as PDF.  No third-party Python packages required.
"""

from __future__ import annotations

import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
CHAR_FILE = os.path.join(PROJECT_DIR, "web", "js", "characters.js")
OUT_HTML = os.path.join(PROJECT_DIR, "characters_by_grade.html")


def parse_characters_js(path: str) -> dict[int, list[dict]]:
    """Parse characters.js and return {grade: [{char, pinyin, meaning}, ...]}."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    grades: dict[int, list[dict]] = {}
    current_grade = None

    for line in text.splitlines():
        stripped = line.strip()

        grade_match = re.match(r"^(\d+)\s*:\s*\[$", stripped)
        if grade_match:
            current_grade = int(grade_match.group(1))
            grades[current_grade] = []
            continue

        if current_grade is not None:
            m = re.search(
                r'char:\s*"(.*?)".*?pinyin:\s*"(.*?)".*?meaning:\s*"(.*?)"',
                stripped,
            )
            if m:
                grades[current_grade].append(
                    {"char": m.group(1), "pinyin": m.group(2), "meaning": m.group(3)}
                )
            if stripped == "],":
                current_grade = None

    return grades


def build_html(grades: dict[int, list[dict]]) -> str:
    total = sum(len(chars) for chars in grades.values())
    grade_sections = []

    for grade in sorted(grades.keys()):
        chars = grades[grade]
        # Character-only grid (compact view)
        char_only = "".join(
            f'<span class="ch" title="{c["pinyin"]} — {c["meaning"]}">{c["char"]}</span>'
            for c in chars
        )
        # Detailed table (pinyin + meaning)
        rows = "".join(
            f'<tr><td class="big">{c["char"]}</td>'
            f'<td>{c["pinyin"]}</td>'
            f'<td>{c["meaning"]}</td></tr>'
            for c in chars
        )
        grade_sections.append(f"""
        <section class="grade">
          <h2>Grade {grade}（{grade}年级）— {len(chars)} characters</h2>
          <div class="chars">{char_only}</div>
          <details>
            <summary>Show pinyin &amp; meanings</summary>
            <table>{rows}</table>
          </details>
        </section>""")

    return f"""<!doctype html>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <title>Chinese Characters by Grade (1–6)</title>
  <style>
    @page {{ size: A4; margin: 16mm; }}
    * {{ box-sizing: border-box; }}
    body {{
      font-family: "PingFang SC", "Noto Sans CJK SC", "Microsoft YaHei", sans-serif;
      color: #222; margin: 0 auto; max-width: 900px; padding: 20px;
      font-size: 11pt; line-height: 1.6;
    }}
    h1 {{ font-size: 22pt; margin: 0 0 4px; }}
    .meta {{ color: #555; margin-bottom: 18px; }}
    .grade {{ margin-bottom: 24px; page-break-inside: avoid; }}
    h2 {{
      font-size: 14pt; margin: 0 0 6px;
      padding-bottom: 4px; border-bottom: 2px solid #6C63FF;
      color: #6C63FF;
    }}
    .chars {{
      font-size: 18pt; letter-spacing: 0.15em;
      word-break: break-all; line-height: 1.8;
    }}
    .ch {{ cursor: default; }}
    .ch:hover {{ background: #fffbcc; border-radius: 4px; }}
    details {{ margin-top: 8px; }}
    summary {{
      cursor: pointer; color: #6C63FF; font-weight: 600;
      margin-bottom: 6px;
    }}
    table {{
      border-collapse: collapse; width: 100%;
      font-size: 10pt;
    }}
    td {{ padding: 2px 8px; border-bottom: 1px solid #eee; }}
    .big {{ font-size: 16pt; text-align: center; width: 40px; }}
    @media print {{
      details {{ display: none; }}
      .ch:hover {{ background: none; }}
    }}
  </style>
</head>
<body>
  <h1>汉字大冒险 — Characters by Grade</h1>
  <div class="meta">Total: {total} characters across {len(grades)} grades.
    Hover over any character to see pinyin &amp; meaning.</div>
  {''.join(grade_sections)}
  <footer style="margin-top:30px;color:#999;font-size:9pt;text-align:center;">
    Generated by hanzi_game_pro / generate_characters_pdf.py
  </footer>
</body>
</html>"""


def main() -> None:
    grades = parse_characters_js(CHAR_FILE)
    html = build_html(grades)
    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(html)
    total = sum(len(c) for c in grades.values())
    print(f"Generated: {OUT_HTML}")
    print(f"  {len(grades)} grades, {total} characters total")
    print("Open in a browser and use File → Print to save as PDF.")


if __name__ == "__main__":
    main()
